=== Chilcano/penrose-server/src/java/org/safehaus/penrose/config/digester-rules.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

Copyright (c) 2000-2005, Identyx Corporation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 
-->

<!ENTITY % rule-elements "bean-property-setter-rule | call-method-rule | call-param-rule |
                   factory-create-rule | object-create-rule |
                   set-properties-rule | set-property-rule | set-top-rule |
                   set-next-rule" >

<!-- digester-rules is the root element. -->
<!ELEMENT digester-rules (pattern | include | bean-property-setter-rule | call-method-rule | call-param-rule | factory-create-rule | object-create-rule | set-properties-rule | set-property-rule | set-top-rule | set-next-rule )*>


<!-- <pattern> defines a matching pattern, or part of a matching pattern. Any
     rule nested in a pattern element prepends its parent's to its pattern.
     Patterns may be recursively nested.
     Example:
       <pattern value="foo">
          <pattern value="bar">
            <object-create-rule pattern="baz" classname="Fubar" />
          </pattern>
       </pattern>

     The above sample fragment defines an ObjectCreateRule associated
     with the pattern "foo/bar/baz".

  Note that the use of pattern elements is optional; an alternative is for
  each rule element to contain a 'pattern' attribute.   -->
<!ELEMENT pattern (pattern | include | bean-property-setter-rule | call-method-rule | call-param-rule |
                   factory-create-rule | object-create-rule |
                   set-properties-rule | set-property-rule | set-top-rule |
                   set-next-rule )*>
<!ATTLIST pattern
    value CDATA #REQUIRED>


<!--
  <include> allows one set of digester rules to be included inside
  another. The 'path' attribute contains the URI of the document to
  include. Inclusion behaves as if the included rules document is
  'macro-expanded' within the outer document.
  Programmatically initialized rules can be included as well, via the
  'class' attribute. The 'class' attribute should contain the name
  of a class that implements
  org.apache.commons.digester.xmlrules.DigesterRulesSource.
-->
<!ELEMENT include EMPTY>
<!ATTLIST include
    path  CDATA #IMPLIED
    class CDATA #IMPLIED>


<!-- Each 'rule' element below corresponds to a concrete subclass
     of org.apache.framework.digester.Rule.
     Each 'rule' element has an optional 'pattern' attribute, which
     defines the pattern for that rule instance. If the rule element
     is nested inside one or more <pattern> elements, those patterns
     will be prepended to the pattern specified in the rule's 'pattern'
     attribute. -->

<!-- Bean Property Setter Rule -->
<!ELEMENT bean-property-setter-rule EMPTY>
<!ATTLIST bean-property-setter-rule
    pattern      CDATA #IMPLIED
    propertyname CDATA #IMPLIED>

<!-- CallMethodRule -->
<!ELEMENT call-method-rule EMPTY>
<!ATTLIST call-method-rule
    pattern    CDATA #IMPLIED
    methodname CDATA #REQUIRED
    paramcount CDATA #IMPLIED
    paramtypes CDATA #IMPLIED>

<!-- 
    CallParamRule 
    attrname - set param from attribute value (cannot be combined with from-stack)
    from-stack - set param from stack (cannot be combined with attrname)
    -->
<!ELEMENT call-param-rule EMPTY>
<!ATTLIST call-param-rule
    pattern  CDATA #IMPLIED
    paramnumber CDATA #REQUIRED
    attrname CDATA #IMPLIED
    from-stack CDATA #IMPLIED>

<!-- 
    FactoryCreateRule 
    
    ignore-exceptions - if this attribute is (ignore case) 'true' then any exceptions
                        thrown by the object create rule will be ignore.
                        This will allow processing to continue.
    -->
<!ELEMENT factory-create-rule EMPTY>
<!ATTLIST factory-create-rule
    pattern   CDATA #IMPLIED
    classname CDATA #REQUIRED
    attrname  CDATA #IMPLIED
    ignore-exceptions  CDATA #IMPLIED> 

<!-- ObjectCreateRule -->
<!ELEMENT object-create-rule EMPTY>
<!ATTLIST object-create-rule
    pattern   CDATA #IMPLIED
    classname CDATA #REQUIRED
    attrname  CDATA #IMPLIED>

<!-- SetPropertiesRule -->
<!ELEMENT set-properties-rule (alias)*>
<!ATTLIST factory-create-rule
    pattern   CDATA #IMPLIED>

<!-- An alias is a custom attribute->property name mapping -->
<!ELEMENT alias EMPTY>
<!ATTLIST alias
 attr-name CDATA #REQUIRED
 prop-name CDATA #IMPLIED>

<!-- SetPropertyRule -->
<!ELEMENT set-property-rule EMPTY>
<!ATTLIST set-property-rule
    pattern   CDATA #IMPLIED
    name      CDATA #IMPLIED
    value     CDATA #IMPLIED>

<!-- SetTopRule -->
<!ELEMENT set-top-rule EMPTY>
<!ATTLIST set-top-rule
    pattern    CDATA #IMPLIED
    methodname CDATA #REQUIRED
    paramtype  CDATA #IMPLIED>

<!-- SetNextRule -->
<!ELEMENT set-next-rule EMPTY>
<!ATTLIST set-next-rule
    pattern    CDATA #IMPLIED
    methodname CDATA #REQUIRED
    paramtype  CDATA #IMPLIED>

=== Chilcano/penrose-server/src/java/org/safehaus/penrose/config/modules-digester-rules.xml
<?xml version="1.0"?>
<!--

 Copyright (c) 2000-2005, Identyx Corporation.
 All rights reserved.

<!DOCTYPE digester-rules PUBLIC
  "-//Jakarta Apache //DTD digester-rules XML V1.0//EN"
  "digester-rules.dtd">
-->
<digester-rules>

	<pattern value="modules">

		<pattern value="module">

			<object-create-rule classname="org.safehaus.penrose.module.ModuleConfig" />

            <set-properties-rule/>

            <call-method-rule pattern="module-name" methodname="setModuleName" paramcount="0" />
            <call-method-rule pattern="module-class" methodname="setModuleClass" paramcount="0" />

			<pattern value="parameter">
				<call-method-rule methodname="setParameter" paramcount="2" />
				<call-param-rule pattern="param-name" paramnumber="0"/>
				<call-param-rule pattern="param-value" paramnumber="1"/>
			</pattern>

			<set-next-rule methodname="addModuleConfig" />

		</pattern>

		<pattern value="module-mapping">

			<object-create-rule classname="org.safehaus.penrose.module.ModuleMapping" />

            <set-properties-rule/>

            <call-method-rule pattern="module-name" methodname="setModuleName" paramcount="0" />
            <call-method-rule pattern="base-dn" methodname="setBaseDn" paramcount="0" />
            <call-method-rule pattern="filter" methodname="setFilter" paramcount="0" />
            <call-method-rule pattern="scope" methodname="setScope" paramcount="0" />

			<set-next-rule methodname="addModuleMapping" />

		</pattern>

	</pattern>

</digester-rules>

=== Chilcano/penrose-server/core/src/java/org/safehaus/penrose/mapping/mapping-digester-rules.xml
<?xml version="1.0"?>
<!--

Copyright (c) 2000-2006, Identyx Corporation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

<!DOCTYPE digester-rules PUBLIC
  "-//Jakarta Apache //DTD digester-rules XML V1.0//EN"
  "digester-rules.dtd">
  
-->
<digester-rules>
<!--
    <pattern value="mapping">
-->
        <pattern value="*/entry">

            <object-create-rule classname="org.safehaus.penrose.directory.EntryMapping" />

            <set-properties-rule>
                <alias attr-name="dn" prop-name="stringDn" />
            </set-properties-rule>

            <call-method-rule pattern="entry-class" methodname="setEntryClass"  paramcount="0" />
            <call-method-rule pattern="description" methodname="setDescription" paramcount="0" />

            <call-method-rule pattern="oc" methodname="addObjectClass" paramcount="0" />

            <pattern value="at">

                <object-create-rule classname="org.safehaus.penrose.directory.AttributeMapping" />
                <set-properties-rule />

                <call-method-rule pattern="binary"   methodname="setBinary"   paramcount="0" />
                <call-method-rule pattern="constant" methodname="setConstant" paramcount="0" />
                <call-method-rule pattern="variable" methodname="setVariable" paramcount="0" />

                <pattern value="expression">
                    <object-create-rule classname="org.safehaus.penrose.mapping.Expression" />
                    <set-properties-rule />

                    <call-method-rule methodname="setScript" paramcount="0" />

                    <set-next-rule methodname="setExpression" />
                </pattern>

                <set-next-rule methodname="addAttributeMapping" />

            </pattern>

            <pattern value="source">

                <object-create-rule classname="org.safehaus.penrose.directory.SourceMapping" />
                <set-properties-rule />
                <call-method-rule pattern="source-name" methodname="setSourceName" paramcount="0" />

                <pattern value="field">
                    <object-create-rule classname="org.safehaus.penrose.directory.FieldMapping" />
                    <set-properties-rule>
                        <alias attr-name="operations" prop-name="stringOperations" />
                    </set-properties-rule>

                    <call-method-rule pattern="binary"   methodname="setBinary"   paramcount="0" />
                    <call-method-rule pattern="constant" methodname="setConstant" paramcount="0" />
                    <call-method-rule pattern="variable" methodname="setVariable" paramcount="0" />

                    <pattern value="expression">
                        <object-create-rule classname="org.safehaus.penrose.mapping.Expression" />
                        <set-properties-rule />

                        <call-method-rule methodname="setScript" paramcount="0" />

                        <set-next-rule methodname="setExpression" />
                    </pattern>

                    <set-next-rule methodname="addFieldMapping" />
                </pattern>

                <pattern value="parameter">
                    <call-method-rule methodname="setParameter" paramcount="2" />
                    <call-param-rule pattern="param-name" paramnumber="0"/>
                    <call-param-rule pattern="param-value" paramnumber="1"/>
                </pattern>

                <set-next-rule methodname="addSourceMapping" />

            </pattern>

            <call-method-rule pattern="handler" methodname="setHandlerName" paramcount="0" />
            <call-method-rule pattern="engine"  methodname="setEngineName"  paramcount="0" />

            <pattern value="aci">

                <object-create-rule classname="org.safehaus.penrose.acl.ACI" />
                <set-properties-rule />
                <call-method-rule pattern="dn"         methodname="setDn"         paramcount="0" />
                <call-method-rule pattern="target"     methodname="setTarget"     paramcount="0" />
                <call-method-rule pattern="attributes" methodname="setAttributes" paramcount="0" />
                <call-method-rule pattern="scope"      methodname="setScope"      paramcount="0" />
                <call-method-rule pattern="action"     methodname="setAction"     paramcount="0" />
                <call-method-rule pattern="permission" methodname="setPermission" paramcount="0" />
                <set-next-rule methodname="addACI" />

            </pattern>

            <pattern value="parameter">
                <call-method-rule methodname="setParameter" paramcount="2" />
                <call-param-rule pattern="param-name"  paramnumber="0"/>
                <call-param-rule pattern="param-value" paramnumber="1"/>
            </pattern>

            <set-next-rule methodname="addEntryMapping" />

        </pattern>
<!--
    </pattern>
-->
</digester-rules>

=== Chilcano/penrose-server/src/java/org/safehaus/penrose/config/mapping-digester-rules.xml
<?xml version="1.0"?>
<!--

Copyright (c) 2000-2005, Identyx Corporation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

<!DOCTYPE digester-rules PUBLIC
  "-//Jakarta Apache //DTD digester-rules XML V1.0//EN"
  "digester-rules.dtd">
-->
<digester-rules>

    <pattern value="mapping">

        <set-properties-rule />

        <pattern value="include">
            <object-create-rule classname="org.safehaus.penrose.mapping.MappingRule" />
            <set-properties-rule />
            <set-next-rule methodname="addContent" />
        </pattern>

        <pattern value="entry">

            <object-create-rule classname="org.safehaus.penrose.mapping.EntryDefinition" />
            <set-properties-rule />

            <call-method-rule pattern="script" methodname="setScript" paramcount="0" />

            <call-method-rule pattern="oc" methodname="addObjectClass" paramcount="0" />

            <pattern value="at">

                <object-create-rule classname="org.safehaus.penrose.mapping.AttributeDefinition" />
                <set-properties-rule />

                <call-method-rule pattern="script" methodname="setScript" paramcount="0" />

                <pattern value="expression">
                    <object-create-rule classname="org.safehaus.penrose.mapping.Expression" />
                    <set-properties-rule />

                    <call-method-rule methodname="setScript" paramcount="0" />

                    <set-next-rule methodname="setExpression" />
                </pattern>

                <set-next-rule methodname="addAttributeDefinition" />

            </pattern>

            <pattern value="source">

                <object-create-rule classname="org.safehaus.penrose.mapping.Source" />
                <set-properties-rule />
                <call-method-rule pattern="source-name" methodname="setSourceName" paramcount="0" />
                <call-method-rule pattern="connection-name" methodname="setConnectionName" paramcount="0" />

                <pattern value="field">
                    <object-create-rule classname="org.safehaus.penrose.mapping.Field" />
                    <set-properties-rule />

                    <call-method-rule pattern="script" methodname="setScript" paramcount="0" />

                    <pattern value="expression">
                        <object-create-rule classname="org.safehaus.penrose.mapping.Expression" />
                        <set-properties-rule />

                        <call-method-rule methodname="setScript" paramcount="0" />

                        <set-next-rule methodname="setExpression" />
                    </pattern>

                    <set-next-rule methodname="addField" />
                </pattern>

                <set-next-rule methodname="addSource" />
            </pattern>

            <pattern value="relationship">

                <object-create-rule classname="org.safehaus.penrose.mapping.Relationship" />
                <call-method-rule pattern="expression" methodname="setExpression" paramcount="0" />
                <set-next-rule methodname="addRelationship" />

            </pattern>

            <pattern value="aci">

                <object-create-rule classname="org.safehaus.penrose.acl.ACI" />
                <set-properties-rule />
                <call-method-rule pattern="dn" methodname="setDn" paramcount="0" />
                <call-method-rule pattern="target" methodname="setTarget" paramcount="0" />
                <call-method-rule pattern="attributes" methodname="setAttributes" paramcount="0" />
                <call-method-rule pattern="scope" methodname="setScope" paramcount="0" />
                <call-method-rule pattern="action" methodname="setAction" paramcount="0" />
                <call-method-rule pattern="permission" methodname="setPermission" paramcount="0" />
                <set-next-rule methodname="addACI" />

            </pattern>

            <pattern value="parameter">
                <call-method-rule methodname="setParameter" paramcount="2" />
                <call-param-rule pattern="param-name" paramnumber="0"/>
                <call-param-rule pattern="param-value" paramnumber="1"/>
            </pattern>

            <pattern value="include">
                <object-create-rule classname="org.safehaus.penrose.mapping.MappingRule" />
                <set-properties-rule />
                <set-next-rule methodname="addChildDefinition" />
            </pattern>

            <set-next-rule methodname="addContent" />

        </pattern>
        
    </pattern>

</digester-rules>

=== Chilcano/penrose-server/src/java/org/safehaus/penrose/config/server-digester-rules.xml
<?xml version="1.0"?>
<!--

 Copyright (c) 1998-2005, Verge Lab., LLC.
 All rights reserved.

<!DOCTYPE digester-rules PUBLIC
  "-//Jakarta Apache //DTD digester-rules XML V1.0//EN"
  "digester-rules.dtd">
-->
<digester-rules>

	<pattern value="server">

		<!-- interpreter -->
		<pattern value="interpreter">
			<object-create-rule classname="org.safehaus.penrose.interpreter.InterpreterConfig" />
			<set-properties-rule/>
            <call-method-rule pattern="interpreter-name" methodname="setInterpreterName" paramcount="0" />
            <call-method-rule pattern="interpreter-class" methodname="setInterpreterClass" paramcount="0" />
			<call-method-rule pattern="description" methodname="setDescription" paramcount="0" />
			<pattern value="parameter">
				<call-method-rule methodname="setParameter" paramcount="2" />
				<call-param-rule pattern="param-name" paramnumber="0"/>
				<call-param-rule pattern="param-value" paramnumber="1"/>
			</pattern>
			<set-next-rule methodname="addInterpreterConfig" />
		</pattern>

		<!-- engine -->
		<pattern value="engine">
			<object-create-rule classname="org.safehaus.penrose.engine.EngineConfig" />
			<set-properties-rule/>
            <call-method-rule pattern="engine-name" methodname="setEngineName" paramcount="0" />
            <call-method-rule pattern="engine-class" methodname="setEngineClass" paramcount="0" />
			<call-method-rule pattern="description" methodname="setDescription" paramcount="0" />
			<call-method-rule pattern="add-handler-class" methodname="setAddHandlerClass" paramcount="0" />
			<call-method-rule pattern="bind-handler-class" methodname="setBindHandlerClass" paramcount="0" />
			<call-method-rule pattern="compare-handler-class" methodname="setCompareHandlerClass" paramcount="0" />
			<call-method-rule pattern="delete-handler-class" methodname="setDeleteHandlerClass" paramcount="0" />
			<call-method-rule pattern="modify-handler-class" methodname="setModifyHandlerClass" paramcount="0" />
			<call-method-rule pattern="modrdn-handler-class" methodname="setModRdnHandlerClass" paramcount="0" />
			<call-method-rule pattern="search-handler-class" methodname="setSearchHandlerClass" paramcount="0" />
			<pattern value="parameter">
				<call-method-rule methodname="setParameter" paramcount="2" />
				<call-param-rule pattern="param-name" paramnumber="0"/>
				<call-param-rule pattern="param-value" paramnumber="1"/>
			</pattern>
			<set-next-rule methodname="addEngineConfig" />
		</pattern>

		<!-- cache -->
		<pattern value="cache">
			<object-create-rule classname="org.safehaus.penrose.cache.CacheConfig" />
			<set-properties-rule/>
            <call-method-rule pattern="cache-name" methodname="setCacheName" paramcount="0" />
            <call-method-rule pattern="cache-class" methodname="setCacheClass" paramcount="0" />
			<call-method-rule pattern="description" methodname="setDescription" paramcount="0" />
			<pattern value="parameter">
				<call-method-rule methodname="setParameter" paramcount="2" />
				<call-param-rule pattern="param-name" paramnumber="0"/>
				<call-param-rule pattern="param-value" paramnumber="1"/>
			</pattern>
			<set-next-rule methodname="addCacheConfig" />
		</pattern>

		<!-- adapter -->
		<pattern value="adapter">
			<object-create-rule classname="org.safehaus.penrose.connection.AdapterConfig" />
			<set-properties-rule/>
            <call-method-rule pattern="adapter-name" methodname="setAdapterName" paramcount="0" />
            <call-method-rule pattern="adapter-class" methodname="setAdapterClass" paramcount="0" />
			<call-method-rule pattern="description" methodname="setDescription" paramcount="0" />
			<set-next-rule methodname="addAdapterConfig" />
		</pattern>

		<!-- connection -->
		<pattern value="connection">
			<object-create-rule classname="org.safehaus.penrose.connection.ConnectionConfig" />
			<set-properties-rule/>
            <call-method-rule pattern="connection-name" methodname="setConnectionName" paramcount="0" />
            <call-method-rule pattern="adapter-name" methodname="setAdapterName" paramcount="0" />
			<call-method-rule pattern="description" methodname="setDescription" paramcount="0" />
			<pattern value="parameter">
				<call-method-rule methodname="setParameter" paramcount="2" />
				<call-param-rule pattern="param-name" paramnumber="0"/>
				<call-param-rule pattern="param-value" paramnumber="1"/>
			</pattern>
			<set-next-rule methodname="addConnectionConfig" />
		</pattern>

		<!-- root -->
		<pattern value="root">
			<set-properties-rule/>
            <call-method-rule pattern="root-dn" methodname="setRootDn" paramcount="0" />
            <call-method-rule pattern="root-password" methodname="setRootPassword" paramcount="0" />
		</pattern>

	</pattern>

</digester-rules>

=== Chilcano/penrose-server/src/java/org/safehaus/penrose/config/sources-digester-rules.xml
<?xml version="1.0"?>
<!--

 Copyright (c) 1998-2005, Verge Lab., LLC.
 All rights reserved.

<!DOCTYPE digester-rules PUBLIC
  "-//Jakarta Apache //DTD digester-rules XML V1.0//EN"
  "digester-rules.dtd">
-->
<digester-rules>

	<pattern value="sources">

        <pattern value="connection">

            <object-create-rule classname="org.safehaus.penrose.mapping.ConnectionConfig" />
            <set-properties-rule>
                <alias attr-name="name" prop-name="connectionName" />
            </set-properties-rule>

            <call-method-rule pattern="adapter-name" methodname="setAdapterName" paramcount="0" />
            <call-method-rule pattern="description" methodname="setDescription" paramcount="0" />

            <pattern value="parameter">
                <call-method-rule methodname="setParameter" paramcount="2" />
                <call-param-rule pattern="param-name" paramnumber="0"/>
                <call-param-rule pattern="param-value" paramnumber="1"/>
            </pattern>

            <pattern value="source">

                <object-create-rule classname="org.safehaus.penrose.mapping.SourceDefinition" />
                <set-properties-rule />

                <call-method-rule pattern="description" methodname="setDescription" paramcount="0" />

                <pattern value="field">

                    <object-create-rule classname="org.safehaus.penrose.mapping.FieldDefinition" />
                    <set-properties-rule />

                    <call-method-rule pattern="original-name" methodname="setOriginalName" paramcount="0" />

                    <set-next-rule methodname="addFieldDefinition" />

                </pattern>

                <pattern value="parameter">
                    <call-method-rule methodname="setParameter" paramcount="2" />
                    <call-param-rule pattern="param-name" paramnumber="0"/>
                    <call-param-rule pattern="param-value" paramnumber="1"/>
                </pattern>

                <set-next-rule methodname="addSourceDefinition" />

            </pattern>

            <set-next-rule methodname="addConnectionConfig" />

        </pattern>

	</pattern>

</digester-rules>
