=== Chilcano/penrose-server/core/src/java/org/safehaus/penrose/connection/connections.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT connections (connection*)>

<!ELEMENT connection (description?, adapter-name, parameter*)>
<!ATTLIST connection name CDATA #REQUIRED>
<!ELEMENT adapter-name (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== Chilcano/penrose-server/samples/pollingConnector/partition/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections 1.1//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="MySQL">
    <adapter-name>JDBC</adapter-name>
    <parameter>
      <param-name>driver</param-name>
      <param-value>com.mysql.jdbc.Driver</param-value>
    </parameter>
    <parameter>
      <param-name>url</param-name>
      <param-value>jdbc:mysql://localhost/example?autoReconnect=true</param-value>
    </parameter>
    <parameter>
      <param-name>user</param-name>
      <param-value>penrose</param-value>
    </parameter>
    <parameter>
      <param-name>password</param-name>
      <param-value>penrose</param-value>
    </parameter>
  </connection>

  <connection name="penrose">
    <adapter-name>JDBC</adapter-name>
    <parameter>
      <param-name>driver</param-name>
      <param-value>com.mysql.jdbc.Driver</param-value>
    </parameter>
    <parameter>
      <param-name>url</param-name>
      <param-value>jdbc:mysql://localhost/penrose?autoReconnect=true</param-value>
    </parameter>
    <parameter>
      <param-name>user</param-name>
      <param-value>penrose</param-value>
    </parameter>
    <parameter>
      <param-name>password</param-name>
      <param-value>penrose</param-value>
    </parameter>
  </connection>

</connections>

=== Chilcano/penrose-server/samples/federation_global/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="LDAP">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>${LDAP_URL}</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>${LDAP_USER}</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>${LDAP_PASSWORD}</param-value>
    </parameter>
  </connection>

</connections>

=== Chilcano/penrose-server/samples/proxy/partition/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections 1.0//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="OpenLDAP">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.factory.initial</param-name>
      <param-value>com.sun.jndi.ldap.LdapCtxFactory</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://localhost/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>cn=Manager,dc=my-domain,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>secret</param-value>
    </parameter>
  </connection>

</connections>

=== Chilcano/penrose-server/samples/ldap_merge/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="AD">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.factory.initial</param-name>
      <param-value>com.sun.jndi.ldap.LdapCtxFactory</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://localhost:389/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>cn=Administrator,cn=Users,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>secret</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.ldap.attributes.binary</param-name>
      <param-value>objectGUID objectSid</param-value>
    </parameter>
  </connection>

  <connection name="LDAP">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.factory.initial</param-name>
      <param-value>com.sun.jndi.ldap.LdapCtxFactory</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://localhost:390/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>cn=Manager,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>secret</param-value>
    </parameter>
  </connection>

</connections>

=== Chilcano/penrose-server/samples/lockout/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="LDAP">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.factory.initial</param-name>
      <param-value>com.sun.jndi.ldap.LdapCtxFactory</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://localhost/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>cn=Manager,dc=my-domain,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>secret</param-value>
    </parameter>
  </connection>

  <connection name="JDBC">
    <adapter-name>JDBC</adapter-name>
    <parameter>
      <param-name>driver</param-name>
      <param-value>com.mysql.jdbc.Driver</param-value>
    </parameter>
    <parameter>
      <param-name>url</param-name>
      <param-value>jdbc:mysql://localhost/lockout?autoReconnect=true</param-value>
    </parameter>
    <parameter>
      <param-name>user</param-name>
      <param-value>penrose</param-value>
    </parameter>
    <parameter>
      <param-name>password</param-name>
      <param-value>penrose</param-value>
    </parameter>
  </connection>

</connections>
