=== Chilcano/penrose-server/common/src/java/org/safehaus/penrose/directory/mapping.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT mapping (entry*)>

<!ELEMENT entry (description?,entry-class?,oc*,at*,source*,link?,handler?,engine?,aci*,parameter*,init?,add?,bind?,compare?,delete?,modify?,modrdn?,search?,unbind?,destroy?)>
<!ATTLIST entry dn CDATA "">
<!ATTLIST entry enabled CDATA #IMPLIED>
<!ATTLIST entry attached CDATA #IMPLIED>
<!ATTLIST entry id CDATA #IMPLIED>
<!ATTLIST entry parentId CDATA #IMPLIED>
<!ELEMENT entry-class (#PCDATA)>
<!ELEMENT init (#PCDATA)>
<!ELEMENT add (#PCDATA)>
<!ELEMENT bind (#PCDATA)>
<!ELEMENT compare (#PCDATA)>
<!ELEMENT delete (#PCDATA)>
<!ELEMENT modify (#PCDATA)>
<!ELEMENT modrdn (#PCDATA)>
<!ELEMENT search (#PCDATA)>
<!ELEMENT unbind (#PCDATA)>
<!ELEMENT destroy (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT oc (#PCDATA)>

<!ELEMENT at (binary|constant|variable|expression)>
<!ATTLIST at name CDATA #REQUIRED>
<!ATTLIST at rdn (true|first|false) "false">
<!ATTLIST at operational (true|false) "false">

<!ELEMENT source (source-name,field*,parameter*)>
<!ATTLIST source name CDATA #REQUIRED>
<!ATTLIST source readOnly CDATA #IMPLIED>
<!ATTLIST source engine CDATA #IMPLIED>
<!ATTLIST source required CDATA #IMPLIED>
<!ATTLIST source add CDATA #IMPLIED>
<!ATTLIST source bind CDATA #IMPLIED>
<!ATTLIST source delete CDATA #IMPLIED>
<!ATTLIST source modify CDATA #IMPLIED>
<!ATTLIST source modrdn CDATA #IMPLIED>
<!ATTLIST source search CDATA #IMPLIED>
<!ELEMENT source-name (#PCDATA)>

<!ELEMENT field (binary|constant|variable|expression)>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field primaryKey (true|first|false) "false">

<!ELEMENT binary (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression foreach CDATA #IMPLIED>
<!ATTLIST expression var CDATA #IMPLIED>

<!ELEMENT link (dn?,partition?)>

<!ELEMENT partition (#PCDATA)>
<!ELEMENT handler (#PCDATA)>
<!ELEMENT engine (#PCDATA)>

<!ELEMENT aci (dn?,target?,attributes?,scope?,action?,permission)>
<!ATTLIST aci subject CDATA #IMPLIED>
<!ELEMENT dn (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT attributes (#PCDATA)>
<!ELEMENT scope (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT permission (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== Chilcano/penrose-server/samples/ad_schema/DIR-INF/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="cn=AD Schema,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.activeDirectory.directory.ActiveDirectorySchemaEntry</entry-class>
    <oc>subentry</oc>
    <oc>subschema</oc>
    <oc>extensibleObject</oc>
    <at name="cn" rdn="true">
      <constant>AD Schema</constant>
    </at>
    <source name="schema"/>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

</mapping>

=== Chilcano/penrose-server/samples/changelog/DIR-INF/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="cn=changelog">
    <oc>top</oc>
    <oc>extensibleObject</oc>
    <at name="cn" rdn="true">
      <constant>changelog</constant>
    </at>
    <at name="o">
      <constant>changelog</constant>
    </at>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="changeNumber=...,cn=changelog">
    <oc>top</oc>
    <oc>changeLogEntry</oc>
    <at name="changeNumber" rdn="true">
      <variable>cl.changeNumber</variable>
    </at>
    <at name="targetDN">
      <variable>cl.targetDN</variable>
    </at>
    <at name="changeType">
      <variable>cl.changeType</variable>
    </at>
    <at name="changes">
      <variable>cl.changes</variable>
    </at>
    <at name="newRDN">
      <variable>cl.newRDN</variable>
    </at>
    <at name="deleteOldRDN">
      <variable>cl.deleteOldRDN</variable>
    </at>
    <at name="newSuperior">
      <variable>cl.newSuperior</variable>
    </at>
    <source name="cl">
      <source-name>changelog</source-name>
      <field name="changeNumber">
        <variable>changeNumber</variable>
      </field>
      <field name="targetDN">
        <variable>targetDN</variable>
      </field>
      <field name="changeType">
        <variable>changeType</variable>
      </field>
      <field name="changes">
        <variable>changes</variable>
      </field>
      <field name="newRDN">
        <variable>newRDN</variable>
      </field>
      <field name="deleteOldRDN">
        <variable>deleteOldRDN</variable>
      </field>
      <field name="newSuperior">
        <variable>newSuperior</variable>
      </field>
    </source>
  </entry>

</mapping>

=== Chilcano/penrose-server/samples/federation_nis/DIR-INF/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="${LDAP_SUFFIX}">
    <entry-class>org.safehaus.penrose.directory.ProxyEntry</entry-class>
    <source>
      <source-name>LDAP</source-name>
    </source>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>                                   
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

</mapping>

=== Chilcano/penrose-server/samples/proxy/partition/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping 1.0//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="dc=Proxy,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>Proxy</constant>
    </at>
    <at name="o">
      <constant>Proxy</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="ou=People,dc=Proxy,dc=Example,dc=com">
    <source name="users" proxy="true">
      <source-name>users</source-name>
    </source>
  </entry>

  <entry dn="uid=manager,ou=People,dc=Proxy,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="uid" rdn="true">
      <constant>manager</constant>
    </at>
    <at name="sn">
      <constant>Manager</constant>
    </at>
    <at name="cn">
      <constant>Manager</constant>
    </at>
  </entry>

  <entry dn="ou=Groups,dc=Proxy,dc=Example,dc=com">
    <source name="groups" proxy="true">
      <source-name>groups</source-name>
    </source>
  </entry>

  <entry dn="cn=Managers,ou=Groups,dc=Proxy,dc=Example,dc=com">
    <oc>groupOfUniqueNames</oc>
    <at name="cn" rdn="true">
      <constant>Managers</constant>
    </at>
    <at name="uniqueMember">
      <constant>uid=manager,ou=People,dc=Proxy,dc=Example,dc=com</constant>
    </at>
    <at name="uniqueMember">
      <constant>uid=admin,ou=People,dc=Proxy,dc=Example,dc=com</constant>
    </at>
  </entry>

</mapping>

=== Chilcano/penrose-server/samples/jdbc_cache/DIR-INF/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="dc=JDBC Cache,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>JDBC Cache</constant>
    </at>
    <at name="o">
      <constant>JDBC Cache</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="ou=Users,dc=JDBC Cache,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Users</constant>
    </at>
  </entry>

  <entry dn="uid=...,ou=Users,dc=JDBC Cache,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="uid" rdn="true">
      <variable>u.uid</variable>
    </at>
    <at name="cn">
      <variable>u.cn</variable>
    </at>
    <at name="sn">
      <variable>u.sn</variable>
    </at>
    <at name="userPassword">
      <variable>u.userPassword</variable>
    </at>
    <source name="u">
      <source-name>cache_users</source-name>
      <field name="uid">
        <variable>uid</variable>
      </field>
      <field name="cn">
        <variable>cn</variable>
      </field>
      <field name="sn">
        <variable>sn</variable>
      </field>
      <field name="userPassword">
        <variable>userPassword</variable>
      </field>
    </source>
  </entry>

  <entry dn="ou=Groups,dc=JDBC Cache,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Groups</constant>
    </at>
  </entry>

  <entry dn="cn=...,ou=Groups,dc=JDBC Cache,dc=Example,dc=com">
    <oc>groupOfUniqueNames</oc>
    <at name="cn" rdn="true">
      <variable>g.cn</variable>
    </at>
    <at name="uniqueMember">
      <variable>ug.uniqueMember</variable>
    </at>
    <source name="g">
      <source-name>cache_groups</source-name>
      <field name="cn">
        <variable>cn</variable>
      </field>
    </source>
    <source name="ug">
      <source-name>cache_usergroups</source-name>
      <field name="cn">
        <variable>g.cn</variable>
      </field>
      <field name="uniqueMember">
        <variable>uniqueMember</variable>
      </field>
    </source>
  </entry>

</mapping>

=== Chilcano/penrose-server/samples/merge/partition/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="dc=Merge,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>Merge</constant>
    </at>
    <at name="o">
      <constant>Merge</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="ou=Users,dc=Merge,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Users</constant>
    </at>
  </entry>

  <entry dn="uid=...,ou=Users,dc=Merge,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="uid" rdn="true">
      <variable>u.username</variable>
    </at>
    <at name="cn">
      <expression>
if (u == void || u == null) return null;
return u.firstName+" "+u.lastName;
      </expression>
    </at>
    <at name="sn">
      <variable>u.lastName</variable>
    </at>
    <at name="userPassword">
      <variable>u.password</variable>
    </at>
    <source name="u">
      <source-name>users</source-name>
      <field name="username">
        <variable>uid</variable>
      </field>
      <field name="firstName">
        <expression>
if (cn == void || cn == null) return null;
int i = cn.lastIndexOf(" ");
return cn.substring(0, i);
        </expression>
      </field>
      <field name="lastName">
        <expression>
if (sn != void &amp;&amp; sn != null) return sn;
if (cn == void || cn == null) return null;
int i = cn.lastIndexOf(" ");
return cn.substring(i+1);
        </expression>
      </field>
      <field name="password">
        <variable>userPassword</variable>
      </field>
    </source>
  </entry>

  <entry dn="uid=...,ou=Users,dc=Merge,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="uid" rdn="true">
      <variable>u2.username</variable>
    </at>
    <at name="cn">
      <expression>
if (u2 == void || u2 == null) return null;
return u2.firstName+" "+u2.lastName;
      </expression>
    </at>
    <at name="sn">
      <variable>u2.lastName</variable>
    </at>
    <at name="userPassword">
      <variable>u2.password</variable>
    </at>
    <source name="u2">
      <source-name>users2</source-name>
      <field name="username">
        <variable>uid</variable>
      </field>
      <field name="firstName">
        <expression>
if (cn == void || cn == null) return null;
int i = cn.lastIndexOf(" ");
return cn.substring(0, i);
        </expression>
      </field>
      <field name="lastName">
        <expression>
if (sn != void &amp;&amp; sn != null) return sn;
if (cn == void || cn == null) return null;
int i = cn.lastIndexOf(" ");
return cn.substring(i+1);
        </expression>
      </field>
      <field name="password">
        <variable>userPassword</variable>
      </field>
    </source>
  </entry>

  <entry dn="ou=Groups,dc=Merge,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Groups</constant>
    </at>
  </entry>

  <entry dn="cn=...,ou=Groups,dc=Merge,dc=Example,dc=com">
    <oc>groupOfUniqueNames</oc>
    <at name="cn" rdn="true">
      <variable>ug.groupname</variable>
    </at>
    <at name="uniqueMember">
      <expression foreach="ug.username" var="username">
return "uid="+username+",ou=Users,dc=Merge,dc=Example,dc=com";
      </expression>
    </at>
    <source name="ug">
      <source-name>usergroups</source-name>
      <field name="groupname">
        <variable>cn</variable>
      </field>
      <field name="username">
        <expression foreach="uniqueMember" var="um">
int i=um.indexOf("=");
int j=um.indexOf(",");
return um.substring(i+1, j);
        </expression>
      </field>
    </source>
  </entry>

</mapping>
