=== Chilcano/penrose-server/common/src/java/org/safehaus/penrose/directory/mapping.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT mapping (entry*)>

<!ELEMENT entry (description?,entry-class?,oc*,at*,source*,link?,handler?,engine?,aci*,parameter*,init?,add?,bind?,compare?,delete?,modify?,modrdn?,search?,unbind?,destroy?)>
<!ATTLIST entry dn CDATA "">
<!ATTLIST entry enabled CDATA #IMPLIED>
<!ATTLIST entry attached CDATA #IMPLIED>
<!ATTLIST entry id CDATA #IMPLIED>
<!ATTLIST entry parentId CDATA #IMPLIED>
<!ELEMENT entry-class (#PCDATA)>
<!ELEMENT init (#PCDATA)>
<!ELEMENT add (#PCDATA)>
<!ELEMENT bind (#PCDATA)>
<!ELEMENT compare (#PCDATA)>
<!ELEMENT delete (#PCDATA)>
<!ELEMENT modify (#PCDATA)>
<!ELEMENT modrdn (#PCDATA)>
<!ELEMENT search (#PCDATA)>
<!ELEMENT unbind (#PCDATA)>
<!ELEMENT destroy (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT oc (#PCDATA)>

<!ELEMENT at (binary|constant|variable|expression)>
<!ATTLIST at name CDATA #REQUIRED>
<!ATTLIST at rdn (true|first|false) "false">
<!ATTLIST at operational (true|false) "false">

<!ELEMENT source (source-name,field*,parameter*)>
<!ATTLIST source name CDATA #REQUIRED>
<!ATTLIST source readOnly CDATA #IMPLIED>
<!ATTLIST source engine CDATA #IMPLIED>
<!ATTLIST source required CDATA #IMPLIED>
<!ATTLIST source add CDATA #IMPLIED>
<!ATTLIST source bind CDATA #IMPLIED>
<!ATTLIST source delete CDATA #IMPLIED>
<!ATTLIST source modify CDATA #IMPLIED>
<!ATTLIST source modrdn CDATA #IMPLIED>
<!ATTLIST source search CDATA #IMPLIED>
<!ELEMENT source-name (#PCDATA)>

<!ELEMENT field (binary|constant|variable|expression)>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field primaryKey (true|first|false) "false">

<!ELEMENT binary (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression foreach CDATA #IMPLIED>
<!ATTLIST expression var CDATA #IMPLIED>

<!ELEMENT link (dn?,partition?)>

<!ELEMENT partition (#PCDATA)>
<!ELEMENT handler (#PCDATA)>
<!ELEMENT engine (#PCDATA)>

<!ELEMENT aci (dn?,target?,attributes?,scope?,action?,permission)>
<!ATTLIST aci subject CDATA #IMPLIED>
<!ELEMENT dn (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT attributes (#PCDATA)>
<!ELEMENT scope (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT permission (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== Chilcano/penrose-server/samples/simple/partition/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="dc=Simple,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>Simple</constant>
    </at>
    <at name="o">
      <constant>Simple</constant>
    </at>
    <aci subject="user">
      <dn>cn=Manager,dc=Simple,dc=Example,dc=com</dn>
      <permission>rwsad</permission>
    </aci>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="cn=Manager,dc=Simple,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="cn" rdn="true">
      <constant>Manager</constant>
    </at>
    <at name="sn">
      <constant>Manager</constant>
    </at>
    <at name="userPassword">
      <constant>secret</constant>
    </at>
  </entry>

  <entry dn="ou=Users,dc=Simple,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Users</constant>
    </at>
  </entry>

  <entry dn="uid=...,ou=Users,dc=Simple,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="uid" rdn="true">
      <variable>u.username</variable>
    </at>
    <at name="cn">
      <variable>u.firstName</variable>
    </at>
    <at name="sn">
      <variable>u.lastName</variable>
    </at>
    <at name="userPassword">
      <variable>u.password</variable>
    </at>
    <at name="memberOf">
      <variable>ug.groupname</variable>
    </at>
    <source name="u">
      <source-name>users</source-name>
      <field name="username">
        <variable>uid</variable>
      </field>
      <field name="firstName">
        <variable>cn</variable>
      </field>
      <field name="lastName">
        <variable>sn</variable>
      </field>
      <field name="password">
        <variable>userPassword</variable>
      </field>
    </source>
    <source name="ug" required="false">
      <source-name>usergroups</source-name>
      <field name="username">
        <variable>u.username</variable>
      </field>
      <field name="groupname">
        <variable>memberOf</variable>
      </field>
    </source>
  </entry>

  <entry dn="ou=Groups,dc=Simple,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Groups</constant>
    </at>
  </entry>

  <entry dn="cn=...,ou=Groups,dc=Simple,dc=Example,dc=com">
    <oc>groupOfUniqueNames</oc>
    <at name="cn" rdn="true">
      <variable>g.groupname</variable>
    </at>
    <source name="g">
      <source-name>groups</source-name>
      <field name="groupname">
        <variable>cn</variable>
      </field>
    </source>
  </entry>

</mapping>

=== Chilcano/penrose-server/samples/lockout/DIR-INF/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="dc=my-domain,dc=com">
    <entry-class>org.safehaus.penrose.directory.ProxyEntry</entry-class>
    <source name="LDAP">
      <source-name>LDAP</source-name>
    </source>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="cn=lockout">
    <oc>extensibleObject</oc>
    <at name="cn" rdn="true">
      <constant>lockout</constant>
    </at>
  </entry>

  <entry dn="account=...,cn=lockout">
    <oc>extensibleObject</oc>
    <at name="account" rdn="true">
      <variable>l.account</variable>
    </at>
    <at name="counter">
      <variable>l.counter</variable>
    </at>
    <at name="timestamp">
      <expression>
return org.safehaus.penrose.lockout.Lock.DATE_FORMAT.format(l.timestamp);
      </expression>
    </at>
    <source name="l">
      <source-name>locks</source-name>
      <field name="account">
        <variable>account</variable>
      </field>
      <field name="counter">
        <variable>counter</variable>
      </field>
      <field name="timestamp">
        <variable>
return new java.sql.Timestamp(org.safehaus.penrose.lockout.Lock.DATE_FORMAT.parse(timestamp));
        </variable>
      </field>
    </source>
  </entry>

</mapping>

=== Chilcano/penrose-server/samples/ldap_cache/partition/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="dc=LDAP Cache,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>LDAP Cache</constant>
    </at>
    <at name="o">
      <constant>LDAP Cache</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="ou=Users,dc=LDAP Cache,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Users</constant>
    </at>
  </entry>

  <entry dn="uid=...,ou=Users,dc=LDAP Cache,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="uid" rdn="true">
      <variable>u.uid</variable>
    </at>
    <at name="cn">
      <variable>u.cn</variable>
    </at>
    <at name="sn">
      <variable>u.sn</variable>
    </at>
    <at name="userPassword">
      <variable>u.userPassword</variable>
    </at>
    <source name="u">
      <source-name>users</source-name>
      <field name="uid">
        <variable>uid</variable>
      </field>
      <field name="cn">
        <variable>cn</variable>
      </field>
      <field name="sn">
        <variable>sn</variable>
      </field>
      <field name="userPassword">
        <variable>userPassword</variable>
      </field>
    </source>
  </entry>

  <entry dn="ou=Groups,dc=LDAP Cache,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Groups</constant>
    </at>
  </entry>

  <entry dn="cn=...,ou=Groups,dc=LDAP Cache,dc=Example,dc=com">
    <oc>groupOfUniqueNames</oc>
    <at name="cn" rdn="true">
      <variable>g.groupname</variable>
    </at>
    <at name="uniqueMember">
      <expression foreach="ug.username" var="username">
return "uid="+username+",ou=Users,dc=LDAP Cache,dc=Example,dc=com";
      </expression>
    </at>
    <source name="g">
      <source-name>groups_cache</source-name>
      <field name="groupname">
        <variable>cn</variable>
      </field>
    </source>
    <source name="ug">
      <source-name>usergroups_cache</source-name>
      <field name="groupname">
        <variable>g.groupname</variable>
      </field>
      <field name="username">
        <expression foreach="uniqueMember" var="um">
int i=um.indexOf("=");
int j=um.indexOf(",");
return um.substring(i+1, j);
        </expression>
      </field>
    </source>
  </entry>

</mapping>

=== Chilcano/penrose-server/samples/jndi/partition/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping 1.0//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="dc=JNDI,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>JNDI</constant>
    </at>
    <at name="o">
      <constant>JNDI</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>
  <entry dn="ou=Users,dc=JNDI,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Users</constant>
    </at>
  </entry>

  <entry dn="uid=...,ou=Users,dc=JNDI,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="uid" rdn="true">
      <variable>u.uid</variable>
    </at>
    <at name="cn">
      <variable>u.cn</variable>
    </at>
    <at name="sn">
      <variable>u.sn</variable>
    </at>
    <at name="givenName">
      <variable>u.givenName</variable>
    </at>
    <at name="ou">
      <variable>u.ou</variable>
    </at>
    <at name="l">
      <variable>u.l</variable>
    </at>
    <at name="mail">
      <variable>u.mail</variable>
    </at>
    <at name="telephoneNumber">
      <variable>u.telephoneNumber</variable>
    </at>
    <at name="facsimileTelephoneNumber">
      <variable>u.facsimileTelephoneNumber</variable>
    </at>
    <at name="roomNumber">
      <variable>u.roomNumber</variable>
    </at>
    <at name="userPassword">
      <variable>u.userPassword</variable>
    </at>
    <source name="u">
      <source-name>users</source-name>
      <field name="uid">
        <variable>uid</variable>
      </field>
      <field name="cn">
        <variable>cn</variable>
      </field>
      <field name="sn">
        <variable>sn</variable>
      </field>
      <field name="givenName">
        <variable>givenName</variable>
      </field>
      <field name="ou">
        <variable>ou</variable>
      </field>
      <field name="l">
        <variable>l</variable>
      </field>
      <field name="mail">
        <variable>mail</variable>
      </field>
      <field name="telephoneNumber">
        <variable>telephoneNumber</variable>
      </field>
      <field name="facsimileTelephoneNumber">
        <variable>facsimileTelephoneNumber</variable>
      </field>
      <field name="roomNumber">
        <variable>roomNumber</variable>
      </field>
      <field name="userPassword">
        <variable>userPassword</variable>
      </field>
    </source>
  </entry>

  <entry dn="ou=Groups,dc=JNDI,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Groups</constant>
    </at>
  </entry>

  <entry dn="cn=...,ou=Groups,dc=JNDI,dc=Example,dc=com">
    <oc>groupOfUniqueNames</oc>
    <at name="cn" rdn="true">
      <variable>g.cn</variable>
    </at>
    <at name="ou">
      <variable>g.ou</variable>
    </at>
    <at name="uniqueMember">
      <expression foreach="g.uniqueMember" var="um">
int i=um.indexOf("=");
int j=um.indexOf(",");
return "uid="+um.substring(i+1, j)+",ou=Users,dc=Example,dc=com";
      </expression>
    </at>
    <source name="g">
      <source-name>groups</source-name>
      <field name="cn">
        <variable>cn</variable>
      </field>
      <field name="ou">
        <variable>ou</variable>
      </field>
      <field name="uniqueMember">
        <expression foreach="uniqueMember" var="um">
int i=um.indexOf("=");
int j=um.indexOf(",");
return "uid="+um.substring(i+1, j)+",ou=People,dc=Example,dc=com";
        </expression>
      </field>
    </source>
  </entry>

</mapping>

=== Chilcano/penrose-server/samples/outlook/partition/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping 1.0//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="dc=Outlook,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>Outlook</constant>
    </at>
    <at name="o">
      <constant>Outlook</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="ou=Users,dc=Outlook,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Users</constant>
    </at>
  </entry>

  <entry dn="uid=...,ou=Users,dc=Outlook,dc=Example,dc=com">

    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>

    <at name="uid" rdn="true">
      <variable>u.username</variable>
    </at>
    <at name="mail">
      <expression>
if (u == void || u == null) return null;
if (u.username == void || u.username == null) return null;
return u.username+"@example.com";
      </expression>
    </at>
    <at name="mailnickname">
      <variable>u.username</variable>
    </at>

    <at name="cn">
      <expression>
if (u == void || u == null) return null;
String cn = u.firstName;
if (u.initials != void &amp;&amp; u.initials != null) cn += " "+u.initials;
cn += " "+u.lastName;
return cn;
      </expression>
    </at>
    <at name="givenName">
      <variable>u.firstName</variable>
    </at>
    <at name="initials">
      <variable>u.initials</variable>
    </at>
    <at name="sn">
      <variable>u.lastName</variable>
    </at>

    <at name="title">
      <variable>u.title</variable>
    </at>
    <at name="company">
      <variable>u.company</variable>
    </at>
    <at name="ou">
      <variable>u.department</variable>
    </at>
    <at name="physicalDeliveryOfficeName">
      <variable>u.office</variable>
    </at>
    <at name="secretary">
      <variable>u.assistant</variable>
    </at>

    <at name="postalAddress">
      <variable>u.businessAddress</variable>
    </at>
    <at name="l">
      <variable>u.businessCity</variable>
    </at>
    <at name="st">
      <variable>u.businessState</variable>
    </at>
    <at name="postalCode">
      <variable>u.businessZipCode</variable>
    </at>
    <at name="co">
      <variable>u.businessCountry</variable>
    </at>

    <at name="telephoneNumber">
      <variable>u.businessPhone</variable>
    </at>
    <at name="telephone-office2">
      <variable>u.businessPhone2</variable>
    </at>
    <at name="facsimileTelephoneNumber">
      <variable>u.businessFax</variable>
    </at>
    <at name="telephone-assistant">
      <variable>u.assistantPhone</variable>
    </at>
    <at name="homePhone">
      <variable>u.homePhone</variable>
    </at>
    <at name="mobile">
      <variable>u.mobile</variable>
    </at>
    <at name="pager">
      <variable>u.pager</variable>
    </at>

    <at name="info">
      <variable>u.notes</variable>
    </at>

    <at name="userPassword">
      <expression>
import org.safehaus.penrose.util.*;

if (u == void || u == null) return null;
if (u.encPassword == void || u.encPassword == null) return null;

byte[] bytes = BinaryUtil.decode("BigInteger", u.encPassword);
return "{SHA}"+BinaryUtil.encode("Base64", bytes);
      </expression>
    </at>

    <at name="manager">
      <expression>
if (m == void || m == null) return null;
if (m.manager == void || m.manager == null) return null;
return "uid="+m.manager+",ou=Users,dc=Outlook,dc=Example,dc=com";
      </expression>
    </at>

    <at name="reports">
      <expression foreach="r.report" var="report">
return "uid="+report+",ou=Users,dc=Outlook,dc=Example,dc=com";
      </expression>
    </at>

    <source name="u">
      <source-name>users</source-name>
      <field name="username">
        <variable>uid</variable>
      </field>

      <field name="firstName">
        <expression>
if (givenName != void &amp;&amp; givenName != null) return givenName;
if (cn == void || cn == null) return null;
int i = cn.indexOf(" ");
if (i &lt; 0) return null;
return cn.substring(0, i);
        </expression>
      </field>
      <field name="initials">
        <expression>
if (initials != void &amp;&amp; initials != null) return initials;
if (cn == void || cn == null) return null;
int i = cn.indexOf(" ");
int j = cn.lastIndexOf(" ");
if (i &lt; 0) return null;
if (j &lt; 0) return null;
return cn.substring(i+1, j);
        </expression>
      </field>
      <field name="lastName">
        <expression>
if (sn != void &amp;&amp; sn != null) return sn;
if (cn == void || cn == null) return null;
int i = cn.lastIndexOf(" ");
if (i &lt; 0) return null;
return cn.substring(i+1);
        </expression>
      </field>

      <field name="title">
        <variable>title</variable>
      </field>
      <field name="company">
        <variable>company</variable>
      </field>
      <field name="department">
        <variable>ou</variable>
      </field>
      <field name="office">
        <variable>physicalDeliveryOfficeName</variable>
      </field>
      <field name="assistant">
        <variable>secretart</variable>
      </field>

      <field name="businessAddress">
        <variable>postalAddress</variable>
      </field>
      <field name="businessCity">
        <variable>l</variable>
      </field>
      <field name="businessState">
        <variable>st</variable>
      </field>
      <field name="businessZipCode">
        <variable>postalCode</variable>
      </field>
      <field name="businessCountry">
        <variable>co</variable>
      </field>

      <field name="businessPhone">
        <variable>telephoneNumber</variable>
      </field>
      <field name="businessFax">
        <variable>facsimileTelephoneNumber</variable>
      </field>
      <field name="homePhone">
        <variable>homePhone</variable>
      </field>
      <field name="mobile">
        <variable>mobile</variable>
      </field>
      <field name="pager">
        <variable>pager</variable>
      </field>

      <field name="notes">
        <variable>info</variable>
      </field>

      <field name="encPassword">
        <expression>import org.safehaus.penrose.util.*;
if (userPassword == void || userPassword == null) return null;

String method = PasswordUtil.getEncryptionMethod(userPassword);
byte[] bytes;

if (method == null) {
    bytes = PasswordUtil.encrypt("SHA", userPassword);

} else if ("SHA".equals(method)) {
    String password = PasswordUtil.getEncryptedPassword(userPassword);
    bytes = BinaryUtil.decode("Base64", password);

} else {
    throw new Exception("Unsupported encryption: "+method);
}

return BinaryUtil.encode("BigInteger", bytes);
        </expression>
      </field>
    </source>

    <source name="m" required="false">
      <source-name>relationships</source-name>
      <field name="manager">
        <expression>
if (manager == void || manager == null) return null;
int i = manager.indexOf("=");
int j = manager.indexOf(",");
return manager.substring(i+1, j);
        </expression>
      </field>
      <field name="report">
        <variable>username</variable>
      </field>
    </source>

    <source name="r" required="false">
      <source-name>relationships</source-name>
      <field name="manager">
        <variable>username</variable>
      </field>
      <field name="report">
        <expression foreach="reports" var="report">
int i = report.indexOf("=");
int j = report.indexOf(",");
return report.substring(i+1, j);
        </expression>
      </field>
    </source>

    <relationship>
      <expression>u.username = m.report</expression>
    </relationship>

    <relationship>
      <expression>u.username = r.manager</expression>
    </relationship>

  </entry>

</mapping>

=== Chilcano/penrose-server/samples/ldap/partition/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping 1.1//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="dc=LDAP,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>LDAP</constant>
    </at>
    <at name="o">
      <constant>LDAP</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="ou=Users,dc=LDAP,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Users</constant>
    </at>
    <at name="description">
      <constant>This is an example of a simple LDAP mapping. All attributes are mapped without any changes.</constant>
    </at>
  </entry>

  <entry dn="uid=...,ou=Users,dc=LDAP,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="uid" rdn="true">
      <variable>u.uid</variable>
    </at>
    <at name="cn">
      <variable>u.cn</variable>
    </at>
    <at name="sn">
      <variable>u.sn</variable>
    </at>
    <at name="userPassword">
      <variable>u.userPassword</variable>
    </at>
    <source name="u">
      <source-name>users</source-name>
      <field name="uid">
        <variable>uid</variable>
      </field>
      <field name="cn">
        <variable>cn</variable>
      </field>
      <field name="sn">
        <variable>sn</variable>
      </field>
      <field name="userPassword">
        <variable>userPassword</variable>
      </field>
    </source>
  </entry>

  <entry dn="ou=All Users,dc=LDAP,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>All Users</constant>
    </at>
    <at name="description">
      <constant>In this example the RDN is generated from the cn attribute, which is not the RDN, of the entries in the target server. If the entry contains multiple values of cn attribute, it will generate multiple virtual entries.</constant>
    </at>
  </entry>

  <entry dn="cn=...,ou=All Users,dc=LDAP,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="uid">
      <variable>u.uid</variable>
    </at>
    <at name="cn" rdn="true">
      <variable>u.cn</variable>
    </at>
    <at name="sn">
      <variable>u.sn</variable>
    </at>
    <at name="userPassword">
      <variable>u.userPassword</variable>
    </at>
    <source name="u">
      <source-name>users</source-name>
      <field name="uid">
        <variable>uid</variable>
      </field>
      <field name="cn">
        <variable>cn</variable>
      </field>
      <field name="sn">
        <variable>sn</variable>
      </field>
      <field name="userPassword">
        <variable>userPassword</variable>
      </field>
    </source>
  </entry>

  <entry dn="ou=Groups,dc=LDAP,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Groups</constant>
    </at>
    <at name="description">
      <constant>In this example the RDN is generated from the RDN of the entries in the target server.</constant>
    </at>
  </entry>

  <entry dn="cn=...,ou=Groups,dc=LDAP,dc=Example,dc=com">
    <oc>groupOfUniqueNames</oc>
    <at name="cn" rdn="true">
      <variable>g.primaryKey.cn</variable>
    </at>
    <at name="cn">
      <variable>g.cn</variable>
    </at>
    <at name="uniqueMember">
      <expression foreach="g.uniqueMember" var="um">
int i=um.indexOf("=");
int j=um.indexOf(",");
return "uid="+um.substring(i+1, j)+",ou=Users,dc=Example,dc=com";
      </expression>
    </at>
    <source name="g">
      <source-name>groups</source-name>
      <field name="cn" primaryKey="true">
        <variable>rdn.cn</variable>
      </field>
      <field name="cn">
        <variable>cn</variable>
      </field>
      <field name="uniqueMember">
        <expression foreach="uniqueMember" var="um">
int i=um.indexOf("=");
int j=um.indexOf(",");
return "uid="+um.substring(i+1, j)+",dc=my-domain,dc=com";
        </expression>
      </field>
    </source>
  </entry>

  <entry dn="ou=All Groups,dc=LDAP,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>All Groups</constant>
    </at>
    <at name="description">
      <constant>In this example the RDN is generated from the cn attribute of the entries in the target server. If an entry contains multiple values of cn attribute, it will generate multiple virtual entries.</constant>
    </at>
  </entry>

  <entry dn="cn=...,ou=All Groups,dc=LDAP,dc=Example,dc=com">
    <oc>groupOfUniqueNames</oc>
    <at name="cn" rdn="true">
      <variable>g.cn</variable>
    </at>
    <at name="uniqueMember">
      <expression foreach="g.uniqueMember" var="um">
int i=um.indexOf("=");
int j=um.indexOf(",");
return "uid="+um.substring(i+1, j)+",ou=Users,dc=Example,dc=com";
      </expression>
    </at>
    <source name="g">
      <source-name>groups</source-name>
      <field name="cn">
        <variable>cn</variable>
      </field>
      <field name="uniqueMember">
        <expression foreach="uniqueMember" var="um">
int i=um.indexOf("=");
int j=um.indexOf(",");
return "uid="+um.substring(i+1, j)+",dc=my-domain,dc=com";
        </expression>
      </field>
    </source>
  </entry>

</mapping>

=== Chilcano/penrose-server/samples/proxy/DIR-INF/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC
  "-//Penrose/DTD Mapping ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/mapping.dtd">

<mapping>

  <entry dn="dc=Proxy,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.ProxyEntry</entry-class>
    <source>
      <source-name>LDAP</source-name>
    </source>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
    <parameter>
      <param-name>attributes</param-name>
      <param-value>uniqueMember</param-value>
    </parameter>
  </entry>

</mapping>
