=== Chilcano/penrose-server/core/src/java/org/safehaus/penrose/config/server.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT server (
        system-property*,
        property*,
        service*,
        schema*,
        interpreter*,
        session*,
        handler*,
        engine*,
        connector*,
        adapter*,
        partition*,
        root
)>

<!ELEMENT system-property (property-name, property-value)>
<!ELEMENT property-name (#PCDATA)>
<!ELEMENT property-value (#PCDATA)>

<!ELEMENT property (property-name, property-value)>

<!ELEMENT service (service-class, description?, parameter*)>
<!ATTLIST service name CDATA #REQUIRED>
<!ATTLIST service enabled CDATA #IMPLIED>
<!ELEMENT service-class (#PCDATA)>

<!ELEMENT schema EMPTY>
<!ATTLIST schema name CDATA #IMPLIED>
<!ATTLIST schema path CDATA #REQUIRED>

<!ELEMENT interpreter (interpreter-name?,interpreter-class?, description?, parameter*)>
<!ATTLIST interpreter name CDATA #IMPLIED>
<!ELEMENT interpreter-name (#PCDATA)>
<!ELEMENT interpreter-class (#PCDATA)>

<!ELEMENT session (description?, parameter*)>
<!ATTLIST session name CDATA #IMPLIED>

<!ELEMENT handler (handler-name?, handler-class?, description?, parameter*)>
<!ATTLIST handler name CDATA #IMPLIED>
<!ELEMENT handler-name (#PCDATA)>
<!ELEMENT handler-class (#PCDATA)>

<!ELEMENT engine (engine-name?, engine-class?, description?, parameter*)>
<!ATTLIST engine name CDATA #IMPLIED>
<!ELEMENT engine-name (#PCDATA)>
<!ELEMENT engine-class (#PCDATA)>

<!ELEMENT connector (connector-class?, description?, parameter*)>
<!ATTLIST connector name CDATA #IMPLIED>
<!ELEMENT connector-class (#PCDATA)>

<!ELEMENT adapter (adapter-class, description?, parameter*)>
<!ATTLIST adapter name CDATA #REQUIRED>
<!ELEMENT adapter-class (#PCDATA)>

<!ELEMENT partition (handler-name?,engine-name?)>
<!ATTLIST partition name CDATA #REQUIRED>
<!ATTLIST partition path CDATA #REQUIRED>

<!ELEMENT root (root-dn, root-password)>
<!ELEMENT root-dn (#PCDATA)>
<!ELEMENT root-password (#PCDATA)>

<!ELEMENT cache-class (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== Chilcano/penrose-server/server/conf/server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE server PUBLIC
  "-//Penrose/DTD Server 1.0//EN"
  "http://penrose.safehaus.org/dtd/server.dtd">

<server>

  <service name="JMX">
    <service-class>org.safehaus.penrose.management.PenroseJMXService</service-class>
    <parameter>
      <param-name>rmiPort</param-name>
      <param-value>1099</param-value>
    </parameter>
    <parameter>
      <param-name>rmiTransportPort</param-name>
      <param-value>40888</param-value>
    </parameter>
  </service>

  <service name="LDAP">
    <service-class>org.safehaus.penrose.ldap.PenroseLDAPService</service-class>
    <parameter> 
      <param-name>ldapPort</param-name> 
      <param-value>10389</param-value> 
    </parameter> 
    <parameter>
      <param-name>enableLdaps</param-name>
      <param-value>false</param-value>
    </parameter>
    <parameter>
      <param-name>ldapsPort</param-name>
      <param-value>10636</param-value>
    </parameter>
    <parameter>
      <param-name>ldapsCertificateFile</param-name>
      <param-value>conf/penrose.keystore</param-value>
    </parameter>
    <parameter>
      <param-name>ldapsCertificatePassword</param-name>
      <param-value>changeit</param-value>
    </parameter>
    <parameter>
      <param-name>allowAnonymousAccess</param-name>
      <param-value>true</param-value>
    </parameter>
  </service>

</server>
