=== Chilcano/penrose-server/core/src/java/org/safehaus/penrose/partition/partition.dtd
<?xml version='1.0' encoding='utf-8'?>

<!--
<!DOCTYPE partition PUBLIC
  "-//Penrose/DTD Partition 1.2//EN"
  "http://penrose.safehaus.org/dtd/partition.dtd">
-->

<!ELEMENT partition (name, description?, source-cache*, entry-cache*)>
<!ATTLIST partition enabled (true|false) "true">

<!ELEMENT entry-cache (cache-class?, description?, parameter*)>
<!ATTLIST entry-cache name CDATA #IMPLIED>

<!ELEMENT source-cache (cache-class?, description?, parameter*)>
<!ATTLIST source-cache name CDATA #IMPLIED>

<!ELEMENT name (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT cache-class (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== Chilcano/penrose-server/samples/pollingConnector/partition/partition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Partition ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/partition.dtd">

<partition enabled="true">

  <name>PollingConnector</name>
  <description>Polling Connector</description>

  <entry-cache>
    <cache-class>org.safehaus.penrose.cache.PersistentEntryCache</cache-class>
    <parameter>
      <param-name>connection</param-name>
      <param-value>penrose</param-value>
    </parameter>
  </entry-cache>

  <source-cache>
    <cache-class>org.safehaus.penrose.cache.PersistentSourceCache</cache-class>
    <parameter>
      <param-name>connection</param-name>
      <param-value>penrose</param-value>
    </parameter>
  </source-cache>

</partition>
