=== Chilcano/penrose-server/core/src/java/org/safehaus/penrose/partition/sources.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT sources (source*,source-sync*)>

<!ELEMENT source (connection-name, description?, field*, parameter*)>
<!ATTLIST source name CDATA #REQUIRED>
<!ELEMENT connection-name (#PCDATA)>

<!ELEMENT field (binary|constant|variable|expression)>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field originalName CDATA #IMPLIED>
<!ATTLIST field primaryKey (true|first|false) "false">
<!ATTLIST field type CDATA #IMPLIED>
<!ATTLIST field length CDATA #IMPLIED>
<!ATTLIST field precision CDATA #IMPLIED>
<!ATTLIST field searchable CDATA #IMPLIED>
<!ATTLIST field unique CDATA #IMPLIED>
<!ATTLIST field index CDATA #IMPLIED>
<!ATTLIST field caseSensitive CDATA #IMPLIED>

<!ELEMENT binary (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression foreach CDATA #IMPLIED>
<!ATTLIST expression var CDATA #IMPLIED>

<!ELEMENT source-sync (class-name?, description?, parameter*)>
<!ATTLIST source-sync name CDATA #IMPLIED>

<!ELEMENT class-name (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== Chilcano/penrose-server/samples/ldap_cache/partition/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>OpenLDAP</connection-name>
    <field name="uid" primaryKey="true"/>
    <field name="cn"/>
    <field name="sn"/>
    <field name="userPassword"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,dc=my-domain,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=*)</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>person,organizationalPerson,inetOrgPerson</param-value>
    </parameter>
  </source>

  <source name="users_cache">
    <connection-name>Cache</connection-name>
    <field name="username" primaryKey="true">
      <variable>users.uid</variable>
    </field>
    <field name="firstName">
      <expression>
if (users == void || users == null) return null;
if (users.cn == void || users.cn == null) return null;
int i = users.cn.lastIndexOf(" ");
return users.cn.substring(0, i);
      </expression>
    </field>
    <field name="lastName">
      <expression>
if (users == void || users == null) return null;
if (users.sn != void &amp;&amp; users.sn != null) return users.sn;
if (users.cn == void || users.cn == null) return null;
int i = users.cn.lastIndexOf(" ");
return users.cn.substring(i+1);
      </expression>
    </field>
    <field name="password">
      <variable>users.userPassword</variable>
    </field>
    <parameter>
      <param-name>table</param-name>
      <param-value>users_cache</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>OpenLDAP</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="uniqueMember"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,dc=my-domain,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=*)</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>groupOfUniqueNames</param-value>
    </parameter>
  </source>

  <source name="groups_cache">
    <connection-name>Cache</connection-name>
    <field name="groupname" primaryKey="true">
      <variable>groups.cn</variable>
    </field>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups_cache</param-value>
    </parameter>
  </source>

  <source name="usergroups_cache">
    <connection-name>Cache</connection-name>
    <field name="groupname" primaryKey="true">
      <variable>groups.cn</variable>
    </field>
    <field name="username" primaryKey="true">
      <expression foreach="groups.uniqueMember" var="um">
int i=um.indexOf("=");
int j=um.indexOf(",");
return um.substring(i+1, j);
      </expression>
    </field>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups_cache</param-value>
    </parameter>
  </source>

  <source-sync name="users">
    <class-name>org.safehaus.penrose.source.ldap.LDAPSourceSync</class-name>
    <parameter>
      <param-name>source</param-name>
      <param-value>users</param-value>
    </parameter>
  </source-sync>

  <source-sync name="groups">
    <class-name>org.safehaus.penrose.source.ldap.LDAPSourceSync</class-name>
    <parameter>
      <param-name>source</param-name>
      <param-value>groups</param-value>
    </parameter>
  </source-sync>

</sources>

=== Chilcano/penrose-server/samples/operational/partition/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources 1.0//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>MySQL</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <field name="creatorsName"/>
    <field name="createTimestamp" type="DATETIME"/>
    <field name="modifiersName"/>
    <field name="modifyTimestamp" type="DATETIME"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/merge/partition/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources 1.0//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>MySQL</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

  <source name="users2">
    <connection-name>MySQL</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>users2</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/cache/partition/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>MySQL</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

  <source name="users_changelog">
    <connection-name>MySQL</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true"/>
    <field name="changeTime"/>
    <field name="changeAction"/>
    <field name="changeUser"/>
    <field name="username"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users_changelog</param-value>
    </parameter>
  </source>

  <source name="users_cache">
    <connection-name>Cache</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users_cache</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups</param-value>
    </parameter>
  </source>

  <source name="groups_cache">
    <connection-name>Cache</connection-name>
    <field name="groupname" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups_cache</param-value>
    </parameter>
  </source>

  <source name="usergroups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true"/>
    <field name="username" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups</param-value>
    </parameter>
  </source>

  <source name="usergroups_cache">
    <connection-name>Cache</connection-name>
    <field name="groupname" primaryKey="true"/>
    <field name="username" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups_cache</param-value>
    </parameter>
  </source>

  <source name="tracker">
    <connection-name>Cache</connection-name>
    <field name="sourceName" primaryKey="true" caseSensitive="true"/>
    <field name="changeNumber" type="INTEGER"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>tracker</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/unix/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>NIS</connection-name>
    <field name="cn"/>
    <field name="sn"/>
    <field name="uid" primaryKey="true"/>
    <field name="uidNumber"/>
    <field name="gidNumber"/>
    <field name="homeDirectory"/>
    <field name="userPassword"/>
    <field name="loginShell"/>
    <field name="gecos"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixAccount</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/passwd</param-value>
    </parameter>
  </source>

  <source name="hosts">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipHostNumber"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipHost</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/hosts</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="gidNumber"/>
    <field name="userPassword"/>
    <field name="memberUid"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/group</param-value>
    </parameter>
  </source>

  <source name="services">
    <connection-name>NIS</connection-name>
    <field name="name"/>
    <field name="cn"/>
    <field name="ipServicePort" primaryKey="true"/>
    <field name="ipServiceProtocol" primaryKey="true"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipService</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/services</param-value>
    </parameter>
  </source>

  <source name="rpcs">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="oncRpcNumber"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>oncRpc</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/rpc</param-value>
    </parameter>
  </source>

  <source name="netids">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="nisNetIdUser"/>
    <field name="nisNetIdGroup"/>
    <field name="nisNetIdHost"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>nisNetId</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/netid</param-value>
    </parameter>
  </source>

  <source name="protocols">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipProtocolNumber"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipProtocol</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/protocols</param-value>
    </parameter>
  </source>

  <source name="aliases">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="rfc822mailMember" originalName="mail"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>nisMailAlias</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/aliases</param-value>
    </parameter>
  </source>

  <source name="netgroups">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="nisNetgroupTriple"/>
    <field name="memberNisNetgroup"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>nisNetgroup</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/netgroup</param-value>
    </parameter>
  </source>

  <source name="ethers">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="macAddress"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ieee802Device</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/ethers</param-value>
    </parameter>
  </source>

  <source name="bootparams">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="bootFile"/>
    <field name="bootParameter"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>bootableDevice</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/bootparams</param-value>
    </parameter>
  </source>

  <source name="networks">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipNetworkNumber"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipNetwork</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/networks</param-value>
    </parameter>
  </source>

  <source name="auto_master">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="automountInformation"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>automount</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/auto.master</param-value>
    </parameter>
  </source>

  <source name="auto_home">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="automountInformation"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>automount</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>/etc/auto.home</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/proxy/partition/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources 1.0//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>SunONE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=People,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>SUBTREE</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=*)</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>SunONE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>SUBTREE</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=*)</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/ldap_merge/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users1">
    <connection-name>AD</connection-name>
    <field name="dn"/>
    <field name="uid" originalName="sAMAccountName" primaryKey="true"/>
    <field name="cn"/>
    <field name="sn"/>
    <field name="givenName"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>user</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>SUBTREE</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=user)</param-value>
    </parameter>
  </source>

  <source name="users2">
    <connection-name>LDAP</connection-name>
    <field name="dn"/>
    <field name="uid" primaryKey="true"/>
    <field name="cn"/>
    <field name="sn"/>
    <field name="givenName"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>account,posixAccount</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>SUBTREE</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=posixAccount)</param-value>
    </parameter>
  </source>

  <source name="groups1">
    <connection-name>AD</connection-name>
    <field name="dn"/>
    <field name="cn" primaryKey="true"/>
    <field name="memberUid" originalName="member"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>group</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>SUBTREE</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=group)</param-value>
    </parameter>
  </source>

  <source name="groups2">
    <connection-name>LDAP</connection-name>
    <field name="dn"/>
    <field name="cn" primaryKey="true"/>
    <field name="memberUid"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>SUBTREE</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=posixGroup)</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/jdbc_ldap/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="jdbc.users">
    <connection-name>MySQL</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

  <source name="ldap.users">
    <connection-name>OpenLDAP</connection-name>
    <field name="uid" primaryKey="true"/>
    <field name="cn"/>
    <field name="sn"/>
    <field name="userPassword"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,dc=my-domain,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
      </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=*)</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>person,organizationalPerson,inetOrgPerson</param-value>
    </parameter>
  </source>

  <source name="jdbc.groups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups</param-value>
    </parameter>
  </source>

  <source name="ldap.groups">
    <connection-name>OpenLDAP</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="uniqueMember"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,dc=my-domain,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=*)</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>groupOfUniqueNames</param-value>
    </parameter>
  </source>

</sources>
