=== Chilcano/penrose-server/core/src/java/org/safehaus/penrose/partition/sources.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT sources (source*,source-sync*)>

<!ELEMENT source (connection-name, description?, field*, parameter*)>
<!ATTLIST source name CDATA #REQUIRED>
<!ELEMENT connection-name (#PCDATA)>

<!ELEMENT field (binary|constant|variable|expression)>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field originalName CDATA #IMPLIED>
<!ATTLIST field primaryKey (true|first|false) "false">
<!ATTLIST field type CDATA #IMPLIED>
<!ATTLIST field length CDATA #IMPLIED>
<!ATTLIST field precision CDATA #IMPLIED>
<!ATTLIST field searchable CDATA #IMPLIED>
<!ATTLIST field unique CDATA #IMPLIED>
<!ATTLIST field index CDATA #IMPLIED>
<!ATTLIST field caseSensitive CDATA #IMPLIED>

<!ELEMENT binary (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression foreach CDATA #IMPLIED>
<!ATTLIST expression var CDATA #IMPLIED>

<!ELEMENT source-sync (class-name?, description?, parameter*)>
<!ATTLIST source-sync name CDATA #IMPLIED>

<!ELEMENT class-name (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== Chilcano/penrose-server/samples/outlook/partition/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources 1.0//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">

    <connection-name>MySQL</connection-name>

    <field name="username" primaryKey="true"/>

    <field name="firstName"/>
    <field name="initials"/>
    <field name="lastName"/>

    <field name="title"/>
    <field name="company"/>
    <field name="department"/>
    <field name="office"/>
    <field name="assistant"/>

    <field name="businessAddress"/>
    <field name="businessCity"/>
    <field name="businessState"/>
    <field name="businessZipCode"/>
    <field name="businessCountry"/>

    <field name="businessPhone"/>
    <field name="businessPhone2"/>
    <field name="businessFax"/>
    <field name="assistantPhone"/>
    <field name="homePhone"/>
    <field name="mobile"/>
    <field name="pager"/>

    <field name="notes"/>

    <field name="encPassword"/>
    <field name="password"/>

    <parameter>
      <param-name>tableName</param-name>
      <param-value>users</param-value>
    </parameter>

  </source>

  <source name="relationships">

    <connection-name>MySQL</connection-name>

    <field name="manager" primaryKey="true"/>
    <field name="report" primaryKey="true"/>

    <parameter>
      <param-name>tableName</param-name>
      <param-value>relationships</param-value>
    </parameter>

  </source>

</sources>

=== Chilcano/penrose-server/samples/nis/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="nis_users">
    <connection-name>NIS</connection-name>
    <field name="cn"/>
    <field name="sn"/>
    <field name="uid" primaryKey="true"/>
    <field name="uidNumber"/>
    <field name="gidNumber"/>
    <field name="homeDirectory"/>
    <field name="userPassword"/>
    <field name="loginShell"/>
    <field name="gecos"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixAccount</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>passwd</param-value>
    </parameter>
  </source>

  <source name="nis_hosts">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipHostNumber"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipHost</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>hosts</param-value>
    </parameter>
  </source>

  <source name="nis_groups">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="gidNumber"/>
    <field name="userPassword"/>
    <field name="memberUid"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>group</param-value>
    </parameter>
  </source>

  <source name="nis_services">
    <connection-name>NIS</connection-name>
    <field name="name"/>
    <field name="cn"/>
    <field name="ipServicePort" primaryKey="true"/>
    <field name="ipServiceProtocol" primaryKey="true"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipService</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>services</param-value>
    </parameter>
  </source>

  <source name="nis_rpcs">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="oncRpcNumber"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>oncRpc</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>rpc</param-value>
    </parameter>
  </source>

  <source name="nis_netids">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="nisNetIdUser"/>
    <field name="nisNetIdGroup"/>
    <field name="nisNetIdHost"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>nisNetId</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>netid</param-value>
    </parameter>
  </source>

  <source name="nis_protocols">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipProtocolNumber"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipProtocol</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>protocols.bynumber</param-value>
    </parameter>
  </source>

  <source name="nis_aliases">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="rfc822mailMember" originalName="mail"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>nisMailAlias</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>aliases</param-value>
    </parameter>
  </source>

  <source name="nis_netgroups">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="nisNetgroupTriple"/>
    <field name="memberNisNetgroup"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>nisNetgroup</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>netgroup</param-value>
    </parameter>
  </source>

  <source name="nis_ethers">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="macAddress"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ieee802Device</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>ethers</param-value>
    </parameter>
  </source>

  <source name="nis_bootparams">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="bootFile"/>
    <field name="bootParameter"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>bootableDevice</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>bootparams</param-value>
    </parameter>
  </source>

  <source name="nis_networks">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipNetworkNumber"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipNetwork</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>networks.byname</param-value>
    </parameter>
  </source>

  <source name="nis_automountMap">
    <connection-name>NIS</connection-name>
    <field name="automountMapName" primaryKey="true"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>automountMap</param-value>
    </parameter>
  </source>

  <source name="nis_automount">
    <connection-name>NIS</connection-name>
    <field name="automountMapName" primaryKey="true"/>
    <field name="automountKey" primaryKey="true"/>
    <field name="automountInformation"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>automount</param-value>
    </parameter>
  </source>
    
</sources>

=== Chilcano/penrose-server/samples/jdbc_cache/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="orig_users">
    <connection-name>MySQL</connection-name>
    <field name="username" primaryKey="true">
      <variable>cache_users.uid</variable>
    </field>
    <field name="firstName">
      <expression>
if (cache_users.cn == void || cache_users.cn == null) return null;
int i = cache_users.cn.lastIndexOf(" ");
if (i &lt; 0) return null;
return cache_users.cn.substring(0, i);
      </expression>
    </field>
    <field name="lastName">
      <expression>
if (cache_users.sn != void &amp;&amp; cache_users.sn != null) return cache_users.sn;
if (cache_users.cn == void || cache_users.cn == null) return null;
int i = cache_users.cn.lastIndexOf(" ");
if (i &lt; 0) return cache_users.cn;
return cache_users.cn.substring(i+1);
      </expression>
    </field>
    <field name="password">
      <variable>cache_users.userPassword</variable>
    </field>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

  <source name="orig_groups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true">
      <variable>cache_groups.cn</variable>
    </field>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups</param-value>
    </parameter>
  </source>

  <source name="orig_usergroups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true">
      <variable>orig_groups.groupname</variable>
    </field>
    <field name="username" primaryKey="true">
      <expression foreach="cache_usergroups.uniqueMember" var="um">
int i=um.indexOf("=");
int j=um.indexOf(",");
return um.substring(i+1, j);
      </expression>
    </field>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups</param-value>
    </parameter>
  </source>

  <source name="cache_users">
    <connection-name>Cache</connection-name>
    <field name="uid" primaryKey="true">
      <variable>orig_users.username</variable>
    </field>
    <field name="cn">
      <expression>
if (orig_users == void || orig_users == null) return null;
return orig_users.firstName+" "+orig_users.lastName;
      </expression>
    </field>
    <field name="sn">
      <variable>orig_users.lastName</variable>
    </field>
    <field name="userPassword">
      <variable>orig_users.password</variable>
    </field>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,dc=JDBC Cache,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

  <source name="cache_groups">
    <connection-name>Cache</connection-name>
    <field name="cn" primaryKey="true">
      <variable>orig_groups.groupname</variable>
    </field>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,dc=JDBC Cache,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups</param-value>
    </parameter>
  </source>

  <source name="cache_usergroups">
    <connection-name>Cache</connection-name>
    <field name="cn" primaryKey="true">
      <variable>cache_groups.cn</variable>
    </field>
    <field name="uniqueMember" primaryKey="true" length="200">
      <expression foreach="orig_usergroups.username" var="username">
return "uid="+username+",ou=Users,dc=JDBC Cache,dc=Example,dc=com";
      </expression>
    </field>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups</param-value>
    </parameter>
  </source>

  <source name="changelog">
    <connection-name>ChangeLog</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true" autoIncrement="true"/>
    <field name="targetDN" type="TEXT"/>
    <field name="changeType" type="VARCHAR" length="255"/>
    <field name="changes" type="TEXT"/>
    <field name="newRDN" type="TEXT"/>
    <field name="deleteOldRDN" type="BOOLEAN"/>
    <field name="newSuperior" type="TEXT"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>changelog</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/shop/partition/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources 1.0//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="categories">
    <connection-name>Shop</connection-name>
    <field name="description" length="100"/>
    <field name="id" primaryKey="true" type="INTEGER" length="5"/>
    <field name="name" unique="true"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>categories</param-value>
    </parameter>
  </source>

  <source name="customer_emails">
    <connection-name>Shop</connection-name>
    <field name="email" primaryKey="true"/>
    <field name="username" index="true"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>customer_emails</param-value>
    </parameter>
  </source>

  <source name="customers">
    <connection-name>Shop</connection-name>
    <field name="encPassword" length="255"/>
    <field name="firstName" primaryKey="true"/>
    <field name="lastName" primaryKey="true"/>
    <field name="password" length="10"/>
    <field name="username" unique="true" length="10"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>customers</param-value>
    </parameter>
  </source>

  <source name="employees">
    <connection-name>Shop</connection-name>
    <field name="encPassword" length="255"/>
    <field name="firstName" primaryKey="true"/>
    <field name="lastName" primaryKey="true"/>
    <field name="password" length="10"/>
    <field name="username" unique="true" length="10"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>employees</param-value>
    </parameter>
  </source>

  <source name="order_details">
    <connection-name>Shop</connection-name>
    <field name="orderId" primaryKey="true" type="INTEGER" length="5"/>
    <field name="price" type="DOUBLE" length="8"/>
    <field name="productId" primaryKey="true" type="INTEGER" length="5"/>
    <field name="quantity" type="INTEGER" length="5"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>order_details</param-value>
    </parameter>
  </source>

  <source name="order_histories">
    <connection-name>Shop</connection-name>
    <field name="description"/>
    <field name="historyDate" primaryKey="true" type="TIMESTAMP"/>
    <field name="orderId" primaryKey="true" type="INTEGER"/>
    <field name="productId" primaryKey="true" type="INTEGER"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>order_histories</param-value>
    </parameter>
  </source>

  <source name="orders">
    <connection-name>Shop</connection-name>
    <field name="customer" length="10"/>
    <field name="employee" length="10"/>
    <field name="id" primaryKey="true" type="INTEGER"/>
    <field name="orderDate" type="TIMESTAMP"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>orders</param-value>
    </parameter>
  </source>

  <source name="products">
    <connection-name>Shop</connection-name>
    <field name="categoryId" type="INTEGER" length="5"/>
    <field name="id" primaryKey="true" type="INTEGER" length="5"/>
    <field name="name" unique="true"/>
    <field name="price" type="DOUBLE" length="8"/>
    <parameter>
      <param-name>tableName</param-name>
      <param-value>products</param-value>
    </parameter>
  </source>
    
</sources>

=== Chilcano/penrose-server/samples/posix/partition/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="posixAccount">
    <connection-name>Posix</connection-name>
    <field name="cn"/>
    <field name="uid" primaryKey="true"/>
    <field name="uidNumber" type="INTEGER"/>
    <field name="gidNumber" type="INTEGER"/>
    <field name="homeDirectory"/>
    <field name="userPassword"/>
    <field name="loginShell"/>
    <field name="gecos"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>posixAccount</param-value>
    </parameter>
  </source>

  <source name="posixGroup">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="gidNumber" type="INTEGER"/>
    <field name="userPassword"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
  </source>

  <source name="posixGroup_memberUid">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="memberUid" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>posixGroup_memberUid</param-value>
    </parameter>
  </source>

  <source name="device">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="serialNumber"/>
    <field name="seeAlso"/>
    <field name="owner"/>
    <field name="ou"/>
    <field name="o"/>
    <field name="l"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>device</param-value>
    </parameter>
  </source>

  <source name="ipHost">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipHostNumber"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipHost</param-value>
    </parameter>
  </source>

  <source name="ipHost_cn">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipHostNumber" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipHost_cn</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/jdbc_cache/partition/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>MySQL</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

  <source name="users_changelog">
    <connection-name>MySQL</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true"/>
    <field name="changeTime"/>
    <field name="changeAction"/>
    <field name="changeUser"/>
    <field name="username"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users_changelog</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups</param-value>
    </parameter>
  </source>

  <source name="usergroups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true"/>
    <field name="username" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups</param-value>
    </parameter>
  </source>

  <source name="users_cache">
    <connection-name>Cache</connection-name>
    <field name="username" primaryKey="true">
      <variable>users.username</variable>
    </field>
    <field name="firstName">
      <variable>users.firstName</variable>
    </field>
    <field name="lastName">
      <variable>users.lastName</variable>
    </field>
    <field name="password">
      <variable>users.password</variable>
    </field>
    <parameter>
      <param-name>table</param-name>
      <param-value>users_cache</param-value>
    </parameter>
  </source>

  <source name="groups_cache">
    <connection-name>Cache</connection-name>
    <field name="groupname" primaryKey="true">
      <variable>groups.groupname</variable>
    </field>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups_cache</param-value>
    </parameter>
  </source>

  <source name="usergroups_cache">
    <connection-name>Cache</connection-name>
    <field name="groupname" primaryKey="true">
      <variable>usergroups.groupname</variable>
    </field>
    <field name="username" primaryKey="true">
      <variable>usergroups.username</variable>
    </field>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups_cache</param-value>
    </parameter>
  </source>

  <source name="tracker">
    <connection-name>Cache</connection-name>
    <field name="sourceName" primaryKey="true" caseSensitive="true"/>
    <field name="changeNumber" type="INTEGER"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>tracker</param-value>
    </parameter>
  </source>

  <source-sync name="users">
    <class-name>org.safehaus.penrose.source.jdbc.JDBCSourceSync</class-name>
    <parameter>
      <param-name>source</param-name>
      <param-value>users</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>users_changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>tracker</param-value>
    </parameter>
  </source-sync>

  <source-sync name="groups">
    <class-name>org.safehaus.penrose.source.jdbc.JDBCSourceSync</class-name>
    <parameter>
      <param-name>source</param-name>
      <param-value>groups</param-value>
    </parameter>
  </source-sync>

  <source-sync name="usergroups">
    <class-name>org.safehaus.penrose.source.jdbc.JDBCSourceSync</class-name>
    <parameter>
      <param-name>source</param-name>
      <param-value>usergroups</param-value>
    </parameter>
  </source-sync>

</sources>

=== Chilcano/penrose-server/samples/ad_schema/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="schema">
    <connection-name>Active Directory</connection-name>
    <field name="lDAPDisplayName" primaryKey="true"/>
    <field name="objectClass"/>
    <field name="attributeID"/>
    <field name="adminDescription"/>
    <field name="attributeSyntax"/>
    <field name="isSingleValued"/>
    <field name="governsID"/>
    <field name="mustContain"/>
    <field name="systemMustContain"/>
    <field name="mayContain"/>
    <field name="systemMayContain"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=Schema,cn=Configuration,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=*)</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/lockout/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="LDAP">
    <connection-name>LDAP</connection-name>
  </source>

  <source name="locks">
    <connection-name>JDBC</connection-name>
    <field name="account" primaryKey="true"/>
    <field name="counter" type="INTEGER"/>
    <field name="timestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>locks</param-value>
    </parameter>
  </source>

</sources>
