=== Chilcano/penrose-server/core/src/java/org/safehaus/penrose/partition/sources.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT sources (source*,source-sync*)>

<!ELEMENT source (connection-name, description?, field*, parameter*)>
<!ATTLIST source name CDATA #REQUIRED>
<!ELEMENT connection-name (#PCDATA)>

<!ELEMENT field (binary|constant|variable|expression)>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field originalName CDATA #IMPLIED>
<!ATTLIST field primaryKey (true|first|false) "false">
<!ATTLIST field type CDATA #IMPLIED>
<!ATTLIST field length CDATA #IMPLIED>
<!ATTLIST field precision CDATA #IMPLIED>
<!ATTLIST field searchable CDATA #IMPLIED>
<!ATTLIST field unique CDATA #IMPLIED>
<!ATTLIST field index CDATA #IMPLIED>
<!ATTLIST field caseSensitive CDATA #IMPLIED>

<!ELEMENT binary (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression foreach CDATA #IMPLIED>
<!ATTLIST expression var CDATA #IMPLIED>

<!ELEMENT source-sync (class-name?, description?, parameter*)>
<!ATTLIST source-sync name CDATA #IMPLIED>

<!ELEMENT class-name (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== Chilcano/penrose-server/samples/federation_global/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="LDAP">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>${LDAP_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="users">
    <connection-name>LDAP</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="uid"/>
    <field name="cn"/>
    <field name="uidNumber"/>
    <field name="gidNumber"/>
    <field name="homeDirectory"/>
    <field name="userPassword"/>
    <field name="loginShell"/>
    <field name="gecos"/>
    <field name="description"/>
    <field name="shadowLastChange"/>
    <field name="shadowMin"/>
    <field name="shadowMax"/>
    <field name="shadowWarning"/>
    <field name="shadowInactive"/>
    <field name="shadowExpire"/>
    <field name="shadowFlag"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>account,posixAccount,shadowAccount</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,${LDAP_SUFFIX}</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>LDAP</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="cn"/>
    <field name="gidNumber"/>
    <field name="userPassword"/>
    <field name="memberUid"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,${LDAP_SUFFIX}</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/changelog/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="changelog">
    <connection-name>MySQL</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true" autoIncrement="true"/>
    <field name="targetDN" type="TEXT"/>
    <field name="changeType" type="VARCHAR" length="255"/>
    <field name="changes" type="TEXT"/>
    <field name="newRDN" type="TEXT"/>
    <field name="deleteOldRDN" type="BOOLEAN"/>
    <field name="newSuperior" type="TEXT"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>changelog</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/federation_ldap/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="LDAP">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>${ldapSuffix}</param-value>
    </parameter>
  </source>
    
  <source name="users">
    <connection-name>LDAP</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="sn"/>
    <field name="givenName"/>
    <field name="sAMAccountName"/>
    <field name="name"/>
    <field name="physicalDeliveryOfficeName"/>
    <field name="telephoneNumber"/>
    <field name="organizationalUnit"/>
    <field name="department"/>
    <field name="c"/>
    <field name="facsimileTelephoneNumber"/>
    <field name="mail"/>
    <field name="displayName"/>
    <field name="otherTelephone"/>
    <field name="objectGUID"/>
    <field name="extensionAttribute1"/>
    <field name="extensionAttribute2"/>
    <field name="countryCode"/>
    <field name="mailNickname"/>
    <field name="info"/>
    <field name="userAccountControl"/>
    <field name="accountExpires"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>user</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=user)</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>${ldapSuffix}</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>LDAP</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="objectGuid"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>group</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=group)</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>${ldapSuffix}</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/ldap/partition/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources 1.0//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>SunONE</connection-name>
    <field name="uid" primaryKey="true"/>
    <field name="cn"/>
    <field name="sn"/>
    <field name="givenName"/>
    <field name="ou"/>
    <field name="l"/>
    <field name="mail"/>
    <field name="telephoneNumber"/>
    <field name="facsimileTelephoneNumber"/>
    <field name="roomNumber"/>
    <field name="userPassword"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=People,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=*)</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>person,organizationalPerson,inetOrgPerson</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>SunONE</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ou"/>
    <field name="uniqueMember"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=*)</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>groupOfUniqueNames</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/ldap_sync/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="source">
    <connection-name>Penrose</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="target">
    <connection-name>OpenLDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="changelog">
    <connection-name>Penrose</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=changelog</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="tracker">
    <connection-name>MySQL</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true"/>
    <field name="changeTimestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>tracker</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/federation_nis/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="LDAP">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>${LDAP_SUFFIX}</param-value>
    </parameter>
  </source>
<!--
  <source name="changes">
    <connection-name>Database</connection-name>
    <field name="id" type="INTEGER" primaryKey="true" autoIncrement="true"
        originalType="INTEGER generated by default as identity"/>
    <field name="time" type="DATETIME"/>
    <field name="title" type="TEXT" originalType="VARCHAR"/>
    <field name="description" type="TEXT" originalType="VARCHAR"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>changes</param-value>
    </parameter>
    <parameter>
      <param-name>create</param-name>
      <param-value>true</param-value>
    </parameter>
  </source>
-->
  <source name="errors">
    <connection-name>Database</connection-name>
    <field name="id" type="INTEGER" primaryKey="true" autoIncrement="true"
        originalType="INTEGER generated by default as identity"/>
    <field name="time" type="DATETIME"/>
    <field name="title" type="TEXT" originalType="VARCHAR"/>
    <field name="description" type="TEXT" originalType="VARCHAR"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>errors</param-value>
    </parameter>
    <parameter>
      <param-name>create</param-name>
      <param-value>true</param-value>
    </parameter>
  </source>

</sources>

=== Chilcano/penrose-server/samples/federation_nss/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="global_users">
    <connection-name>LDAP</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="uid"/>
    <field name="cn"/>
    <field name="uidNumber"/>
    <field name="gidNumber"/>
    <field name="homeDirectory"/>
    <field name="userPassword"/>
    <field name="loginShell"/>
    <field name="gecos"/>
    <field name="description"/>
    <field name="shadowLastChange"/>
    <field name="shadowMin"/>
    <field name="shadowMax"/>
    <field name="shadowWarning"/>
    <field name="shadowInactive"/>
    <field name="shadowExpire"/>
    <field name="shadowFlag"/>
    <field name="seeAlso"/>
    <field name="seeAlsoObjectGUID"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>account,posixAccount,shadowAccount</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,${GLOBAL_SUFFIX}</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="nis_users">
    <connection-name>LDAP</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="uid"/>
    <field name="cn"/>
    <field name="uidNumber"/>
    <field name="gidNumber"/>
    <field name="homeDirectory"/>
    <field name="userPassword"/>
    <field name="loginShell"/>
    <field name="gecos"/>
    <field name="description"/>
    <field name="shadowLastChange"/>
    <field name="shadowMin"/>
    <field name="shadowMax"/>
    <field name="shadowWarning"/>
    <field name="shadowInactive"/>
    <field name="shadowExpire"/>
    <field name="shadowFlag"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>account,posixAccount,shadowAccount</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,${NIS_SUFFIX}</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="ad_users">
    <connection-name>AD</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="objectGuid"/>
    <field name="userAccountControl"/>
    <field name="accountExpires"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>user</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=user)</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>${AD_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="global_groups">
    <connection-name>LDAP</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="cn"/>
    <field name="gidNumber"/>
    <field name="userPassword"/>
    <field name="memberUid"/>
    <field name="description"/>
    <field name="seeAlso"/>
    <field name="seeAlsoObjectGUID"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,${GLOBAL_SUFFIX}</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="nis_groups">
    <connection-name>LDAP</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="cn"/>
    <field name="gidNumber"/>
    <field name="userPassword"/>
    <field name="memberUid"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,${NIS_SUFFIX}</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="ad_groups">
    <connection-name>AD</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="objectGuid"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>group</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=group)</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>${AD_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_hosts">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Hosts,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_services">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Services,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_rpcs">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=RPCs,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_netids">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=NetIDs,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_protocols">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Protocols,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_aliases">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Aliases,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_netgroups">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Netgroups,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_ethers">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Ethers,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_bootparams">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=BootParams,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_networks">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Networks,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="nis_automounts">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Automounts,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

  <source name="profile">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Profile,${NIS_SUFFIX}</param-value>
    </parameter>
  </source>

</sources>
